# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mithorium-common-4.19/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter Mi439-4.19,$(TARGET_DEVICE)),)

endif
